### ISSUE TITLE
entry-form water

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#1]
## Value Preposition

**As a** user (fisherman)
**I need** to document my fishing experiences and results
**to be able to** track fish populations and to fish more efficiently

## Description

Step 2:

![capstone-form-water](https://user-images.githubusercontent.com/98737059/159954067-4460062d-74fe-47ec-bc9f-16c1372ff156.png)

(form values get saved to the diary as a card)

## Acceptance Criteria

- [x] on Submit the form values get saved to the diary as a card
- [x] required inputs have a max. length of 25 characters
- [x] no future date
- [x] water temperature is a number between -5 and 50
- [x] shows warning when required inputs are not filled

## Tasks

(for developers team)

- [x] create branch entry-form
- [x] create entry-form component
- [x] add entry-form storybook and specs
- [x] create entry-form title
- [x] create entry-form with its inputs and labels
- [x] ,,date" and ,,water" is required
- [x] create submit button as a component
- [x] build map logic to create cards in diary page when clicking on the submit button
- [x] build button storybook and specs
- [x] add entry-form and button to App
