### ISSUE TITLE
Add localstorage

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#10]
## Value Preposition

**As a User**
**I need** to save my written cards
**to be able to** access at any time I want

## Description

- add local storage to be able to render more cards without replacing them
- the data will be saved and still be shown after closing and reopening the app

## Acceptance Criteria

- [x] the data will be saved and and still be shown after closing and reopening the app

## Tasks

- [x] create new branch
- [x] switch to new branch
- [x] add local storage
- [x] update styling (gap)
