### ISSUE TITLE
Add multiple catches

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#20]
## Value Preposition

**As a User/Fisherman** 
**I need** to submit multiple catches at a time
**to be able to** document every single catch I had at one day

## Description

![capstone-catches](https://user-images.githubusercontent.com/98737059/161632326-43d3c4b9-8520-4adf-86b8-a9b464ea08fb.png)

## Acceptance Criteria

- [ ] on Add catch click the filled inputs are saved
- [ ] onClick you see a preview of every catch your already made
- [ ] by submitting the form every single catch gets shown in a card

## Tasks

(for developers team)

- [ ] work on new branch
- [ ] create an extra useState for catches only
- [ ] create preview logic
- [ ] multiple catches should be possible to save in the useState
- [ ] create map logic to show every catch in the card
- [ ] add delete button to be able to delete a created catch (does not have to work yet)
