### ISSUE TITLE
Delete cards and preview catches

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#21]
## Value Preposition

**As a User**
**I need** to delete my cards (and preview catches)
**to be able to** delete wrong or unnecessary cards  (and preview catches)

## Description

![capstone-delete](https://user-images.githubusercontent.com/98737059/161633835-e9d78143-ecac-4d5e-ad78-3907597cb823.png)

## Acceptance Criteria

- [ ] onClick delete button the clicked card and preview catch gets deleted
- [ ] onClick delete cards the user gets asked again to delete or to keep the card
- [ ] onClick delete preview catch the clicked catch gets deleted from useState
- [ ] deleted preview catches do not get rendered in card
- [ ] check on multiple device for functionality

## Tasks

- [ ] work on new branch
- [ ] set delete Button
- [ ] create delete logic for cards and preview catches
