### ISSUE TITLE
Add back-end

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#22]
## Value Preposition

**As a User** 
**I need** to save my fishing data in a back-end
**to be able to** access it at any time at any place I want and to save it properly

## Description

back-end to save users cards for good

## Acceptance Criteria

- [ ] all cards and all fishing data is saved after submitting the form
- [ ] whenever the page is new loaded the data is still there
- [ ] data is save in back-end
- [ ] add and delete functions all still work

## Tasks

- [ ] create back-end logic
- [ ] use MongoDB
