### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#28]
## Value Preposition

**As a User**
**I need** to have a delete confirmation
**to be able to** avoid deleting cards by mistake

## Description

![capstone-delete-modal](https://user-images.githubusercontent.com/98737059/162691568-eae44494-3850-4737-9fe7-3026a669daee.png)

## Acceptance Criteria

- [ ] onDelte confirmation card pops up
- [ ] onConfirm the card is deleted (from backend) and the confirmation card closes
- [ ] onCancel the card is not deleted and the confirmation card closes

## Tasks

- [ ] work on new branch
- [ ] create confirmation page and file structure
- [ ] write functions for "confirm" and "cancel"
- [ ] create confirmation for deleting cards and catches
