### ISSUE TITLE
Navigation between diary and entry-form

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#3]
## Value Preposition

**As a** user
**I need** to navigate in to the form-entry page
**to be able to** create new entries

## Description

Step 1:

![capstone-nav-entries_entry](https://user-images.githubusercontent.com/98737059/159908057-40ee5ebe-7d3f-4b57-a90f-051b115a6775.png)

## Acceptance Criteria

- [ ] navigate to entry-form by clicking on the plus icon
- [ ] navigate to diary page by clicking on the entries icon or the back arrow icon

## Tasks

- [ ] create branch navigation
- [ ] create router pages (diary, form)
- [ ] create navigation component and spec
- [ ] add navigation to App
- [ ] build navigation bar with two icons
- [ ] add the back arrow icon to the entry-form above the title
- [ ] build navigation logic between diary page and form page
