### ISSUE TITLE
Add LogIn and SignUp Page

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#33]
## Value Preposition

**As a User**
**I need** to have a profile
**to be able to** use only my own data

## Description

- LoginPage with username and password and link to SignupPage
- SignupPage with first name, last name, username, password
- ProfilePage with statistics and Greeting

## Acceptance Criteria

- [x] onLogin profile data is set
- [x] onLogin first name of profile is shown at HomePage and ProfilePage
- [x] onSignup profile data gets saved to backend
- [x] a new user can log in with his data
- [x] onClick Signup button navigate to SignupPage
- [x] when adding a card or a catch statistics on ProfilePage changes

## Tasks

(for developers team)

- [x] work on new branch
- [x] create Pages
- [x] add new folder for backend
- [x] create login and profile logic (token)
- [x] add  first statistics to ProfilePage
