### ISSUE TITLE
Each profile has accesibility to only its own fishing data

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#34]
## Value Preposition

**As a User**
**I need** to have my own fishing data 
**to be able to** not share my data with all other users

## Description

- each profile only sees its own created data

## Acceptance Criteria

- [ ] onSubmit new fishing data profile only sees his own cards and catches
- [ ] each Profile has its own statistics made up from their own data

## Tasks

(for developers team)

- [ ] work on new branch
- [ ] add backend logic that each profile has its ,,own backend''
- [ ] add author to each card and catch
- [ ] only show the cards and catches of the belonging profile
