### ISSUE TITLE
entry-form enahncement  with weather inputs

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#4]
## Value Preposition

**As a** user (fisherman)
**I need** to document my fishing experiences and results
**to be able to** track fish populations and to fish more efficiently

## Description

Step 3:

![capstone-form-weather](https://user-images.githubusercontent.com/98737059/159908810-2b17fa47-9062-4446-abff-ea7a27246187.png)

(form values get saved to the diary as a card)

## Acceptance Criteria

- [x] on Submit the form values get saved to the diary as a card
- [x] inputs have a max. length of 300 characters
- [x]  temperature (weather) is a number between -50 and 50
- [x] air pressure is a number between 850 and 1150
- [x] wind speed is a number >/= 0

## Tasks

(for developers team)

- [x] edit in branch entry-form
- [x] create more inputs and labels so that the form have more inputs
- [x] add weather part to cards

**Comment by PReichetanz** [comment]
As far as I understand this story, it enhances your second story (and in particular, your form), is this correct?
Currently, the value proposition of story 2 and 3 are the same.

I think you should adapt your value proposition in order to make clear that, when finishing the story, you have a form with more inputs.

**Comment by CasparVelsen** [comment]
Yes, I am enhancing my previous story (my form) with more inputs. Thanks for the suggestion. I'll do that
