### ISSUE TITLE
entry-form catch

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#5]
## Value Preposition

**As a User**
**I need** have an entry form for my catches
**to be able to** document my caught fish

## Description

Step: 4

![capstone-form-catch1](https://user-images.githubusercontent.com/98737059/159948963-ba896872-020a-44f2-b559-22f8d1abdcac.png)

(form values get saved to the diary as a card)

## Acceptance Criteria

- [x] on Submit the form values get saved to the diary as a card
- [x] inputs have a max. length of 100 characters (notes 300)
- [x] length and weight is number > 0
- [x] ,,total bites" and ,,lost fish" are a number

## Tasks

- [x] on Submit the form values get saved to the diary as a card
- [x] inputs have a max. length of 300 characters
- [x] see that catch date gets transformed to a card like the previous data
