### ISSUE TITLE
expanded card showing more informations

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#6]
## Value Preposition

**As a User**
**I need** to expand the preview cards
**to be able to** see all infos

## Description

![capstone-expanded-card](https://user-images.githubusercontent.com/98737059/159959308-77eba952-76fa-46d9-ad0d-cf895756f8f6.png)

## Acceptance Criteria

- [x] nothing yet

## Tasks

(for developers team)

- [x] when clicking on the arrow the card expands
- [x] all infos are listed
- [x] cards height: fit-content (no scrowling)

**Comment by CasparVelsen** [comment]
issue not finished
