### ISSUE TITLE
Change form layout to a ,,five step form''

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/capstone-project#8]
## Value Preposition

**As a User**
**I need** a guidance through the form
**to be able to** fill in the form in a simpler and quicker way

### improve user-experience

![capstone-5steps-form](https://user-images.githubusercontent.com/98737059/160370988-c8464522-8996-4e81-84f5-5a7e61c81e3e.png)

## Acceptance Criteria

- [ ] by clicking on ''next" the user gets navigated through the form
- [ ] onNext is only allowed if all required inputs are filled
- [ ] there is a text that indicates on which page the user is currently
- [ ] onSubmit the form value gets displayed as a card on the homepage

## Tasks

(for developers team)

- [ ] create a new branch
- [ ] switch to branch ! 
- [ ] take over structure from previous form style, just split the form into five parts:
- [ ]  General 
- [ ] Water 
- [ ] Weather 
- [ ] Catch 
- [ ] Summary
- [ ] create logic to navigate through the form
- [ ] add "next" buttons
- [ ] add indicator (eg. 2 of 5)
